
fn Test () {
	try {
		a = 1 * ""
	} catch (err) {
		print(err)
		print(err.message)
		print(err.stackTrace)
	}
}

Test()