
try {
	//error("lol fuck you")
} catch (err) {
	print("caught error: " + err)
}